### ISSUE TITLE
slip_models.pkl

### ISSUE THREAD

**Issue by yjydiancom** [omron-sinicx/safe-rover-navi#1]
I'm sorry to interrupt, I didn't quite understand how files like slip_models.pkl are generated.

**Comment by masafumiendo** [comment]
Hi! Thank you for your question. In our implementation, `create_data.py` is a script that creates terrain maps, including their associated colors and heights, as well as latent slip models assigned to each terrain class. The `SlipModelsGenerator` class plays this role either by randomly generating latent slip models or loading generated slip models. You can try to run the script to see how all the files are generated. If there are any questions, please let me know!

**Comment by yjydiancom** [comment]
Ok, thanks for the answer, I didn't look at the code carefully, I thought it just generated the map.
