### ISSUE TITLE
MGP model

### ISSUE THREAD

**Issue by yjydiancom** [omron-sinicx/safe-rover-navi#2]
May I ask how you trained the MGP model? I only see that you train the GP models corresponding to each terrain in load_models in the SlipModelsGenerator class.

**Comment by yjydiancom** [comment]
I hope you can show me where cvar is used to assess risk, would really appreciate an answer!!!!

**Comment by masafumiendo** [comment]
Hi! Thank you for your inquiry, and I apologize for my late response.

You do not need to train the MGP model—it is the result of fusing multiple GP models weighted by the classification likelihoods from the terrain classifier, as denoted in eq. (5) from our paper.

**Comment by yjydiancom** [comment]
OK！thanks！
