### ISSUE TITLE
gtm

### ISSUE THREAD

**Issue by yjydiancom** [omron-sinicx/safe-rover-navi#3]
Hi, I would also like to ask about gtm, is it not possible to run cvar again in gtm mode?

**Comment by yjydiancom** [comment]
![image](https://github.com/omron-sinicx/safe-rover-navi/assets/91858119/1ccf415b-076c-45db-87e9-d083fdc5435a)
![image](https://github.com/omron-sinicx/safe-rover-navi/assets/91858119/0b7f9d7f-67af-4057-b173-b65103bed26c)
![env_00_0000](https://github.com/omron-sinicx/safe-rover-navi/assets/91858119/58a38e7b-dab7-418a-a4d5-2e9effcfaf70)

Does this produce a result that is a path found under real slip?

**Comment by masafumiendo** [comment]
Hi! Thank you for your inquiry. If you set `type_model="gtm"`, the planner refers to noisy slip observations. So, yes, your result should indicate a path found under a real slip. You can check how planning costs are estimated during path planning in the `CostEstimator` class.

**Comment by yjydiancom** [comment]
Okay, thanks for your patience in answering!I'd also like to ask what terrain are the ten terrains you have set up? I don't see a corresponding label.

**Comment by masafumiendo** [comment]
The ten terrains are arbitrary terrain classes, and you can see that the number of terrain classes is set as `n_terrains` during data generation. https://github.com/omron-sinicx/safe-rover-navi/blob/7a582ce90c8f836417d5c9b5bf14c855810862f6/scripts/create_data.py#L78

Feel free to ask questions if there are any; thank you for your inquiry.
